FROM python:3.9-slim

WORKDIR /app

COPY client-requirements.txt .

RUN pip install -r client-requirements.txt

COPY client.py .

EXPOSE 5001

CMD ["python", "client.py"]

# sudo docker build . -t client_image -f Dockerfile-client
# sudo docker run --rm -ti --name client -p 5001:5001 client_image